language: ruby

sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - ruby-head
  - jruby-1.7.22
  - jruby-9.0.1.0
  - rbx-19mode
  - rbx-2

matrix:
  allow_failures:
    - rvm: jruby-1.7.22
    - rvm: jruby-9.0.1.0
    - rvm: rbx-2
